image:
  file: .gitpod.Dockerfile

ports:
  - name: Rails server
    port: 3000
    onOpen: open-preview
  - name: PostgreSQL server
    port: 5432
    onOpen: ignore

tasks:
  - name: Installing Dependencies
    init: |
      bundle install &&
      yarn install
  - name: create database & start server
    command: |
      rake db:create
      rails server -b 0.0.0.0

vscode:
  extensions:
    - rebornix.ruby

jetbrains:
  rubymine:
    prebuilds:
      version: both
